global using OfficeManagerDataAccess.PersonManager.PersonManagerData;
global using OfficeManagerDataAccess.PersonManager.PersonManagerHandlers;
global using OfficeManagerDataAccess.PersonManager.PersonManagerInterfaces;
global using OfficeManagerDataAccess.PersonManager.PersonManagerModels;
global using OfficeManagerUI.Components.Shared.BasePageClasses.People;
global using OfficeManagerUI.Models.PersonManagerModels;